
title: Agbo Perpetual 

logo: Asset/My_picture_1.jpeg

description: data analyst

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: Agboperpetual835@gmail.com


