
title: Agbo Perpetual 

logo: <img width="350" height="200" src="Asset/U_cert.png">

description: Data science and AI in agriculture - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: Agboperpetual835@gmail.com


