
title: Agbo Perpetual 

logo: Asset/My_picture_1.jpeg

📞 Contact 
 E-mail: <a href="agboperpetual835@gmail.com">agboperpetual835@gmail.com</a> | 
 LinkedIn: <a href="https://www.linkedin.com/in/allan-victor-6919b4152/" target="_blank">Visit Page</a> | 


#description: data analyst

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: Agboperpetual835@gmail.com


