
title: Agbo Perpetual 

logo: Asset/My_picture_1.jpeg
 
 E-mail: "agboperpetual835@gmail.com" 
 LinkedIn: 


#description: data analyst

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 





