
title: Agbo Perpetual 

logo: width="460" height="300""My_picture_1.jpeg"

description: Data science and AI in agriculture - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: Agboperpetual835@gmail.com


