title: Agbo Perpetual 
email: agboperpetual835@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
twitter_username: billraymonde
github_username:  

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed



